//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrbitalSimWPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Not finding bodies CSV file")]
        public string NoBodiesCSVFile {
            get {
                return ((string)(this["NoBodiesCSVFile"]));
            }
            set {
                this["NoBodiesCSVFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Properties\\Bodies.csv")]
        public string BodiesCSVFile {
            get {
                return ((string)(this["BodiesCSVFile"]));
            }
            set {
                this["BodiesCSVFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Properties\\SimBodies.csv")]
        public string SimBodiesCSVFile {
            get {
                return ((string)(this["SimBodiesCSVFile"]));
            }
            set {
                this["SimBodiesCSVFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unable to save bodies CSV file")]
        public string NoSaveBodiesCSV {
            get {
                return ((string)(this["NoSaveBodiesCSV"]));
            }
            set {
                this["NoSaveBodiesCSV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gathering ephemerides from JPL Horizons")]
        public string GatheringEphemerides {
            get {
                return ((string)(this["GatheringEphemerides"]));
            }
            set {
                this["GatheringEphemerides"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ssd.jpl.nasa.gov/horizons.cgi")]
        public string HorizonsCheckURL {
            get {
                return ((string)(this["HorizonsCheckURL"]));
            }
            set {
                this["HorizonsCheckURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ssd.jpl.nasa.gov/horizons_batch.cgi?batch=1&COMMAND=\'{Command}\'&CENTER=\'@" +
            "0\'&MAKE_EPHEM=\'YES\'&EPHEM_TYPE=\'VECTOR\'&VEC_TABLE=\'3\'&START_TIME=\'{StartTime}\'&S" +
            "TOP_TIME=\'{StopTime}\'&STEP_SIZE=\'1h\'&OUT_UNITS=\'KM-S\'&CSV_FORMAT=\'YES\'")]
        public string HorizonsEphemerisURL {
            get {
                return ((string)(this["HorizonsEphemerisURL"]));
            }
            set {
                this["HorizonsEphemerisURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No connection to JPL Horizons")]
        public string NoHorizonsConnection {
            get {
                return ((string)(this["NoHorizonsConnection"]));
            }
            set {
                this["NoHorizonsConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12000000000")]
        public double AxisLength {
            get {
                return ((double)(this["AxisLength"]));
            }
            set {
                this["AxisLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Properties\\SavedBodyListFile")]
        public string SavedBodyListFile {
            get {
                return ((string)(this["SavedBodyListFile"]));
            }
            set {
                this["SavedBodyListFile"] = value;
            }
        }
    }
}
